#pragma once

#include <cstring>
#include <string>

#include <nlohmann/json.hpp>

#include "Utils/String.h"

namespace fc::Assets
{

/// @brief Runtime identifier for a registered asset, generated by hashing its type and string ID.
using AssetId = uint32_t;

/// @brief Maximum length of an asset's string ID, excluding the null terminator.
inline constexpr size_t MAX_ASSET_ID_LENGTH = 63;

/// @brief Maximum length of an asset's path relative to the asset root, excluding the null terminator.
inline constexpr size_t MAX_ASSET_PATH_LENGTH = 255;

/// @brief Describes a single registered asset.
struct Asset
{
    /// @brief The ID string found in the asset manifest.
    std::string mIdString = {};

    /// @brief The hashed ID, generated from '<type>:<id string>`.
    AssetId mId = 0;

    /// @brief The path to the manifest, relative to the asset root.
    std::string mRelativePath = {};

    /// @brief The absolute path to the manifest.
    std::string mAbsolutePath = {};

    virtual ~Asset() = default;
};

struct AssetType
{
    char mName[64] = {};
    Asset* (*FromJson)(const nlohmann::json& json, const std::string& directoryPath);
};

inline void FromJson(const nlohmann::json& json, Asset* asset)
{
    json.at("id").get_to(asset->mIdString);
}

/// @brief Generates the runtime ID for an asset from its type and string ID.
inline AssetId MakeAssetId(const char* idString, const AssetType& type)
{
    if (idString == nullptr)
        return 0;

    Utils::String::HashAccumulator hash;
    hash.Add(type.mName);
    hash.Add(":");
    hash.Add(idString, std::strlen(idString));
    return hash.Value();
}

} // namespace fc::Assets
